name: Flutter Format Check

on:
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/flutter/bin/cache/**') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
            
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: flutter analyze