name: Flutter Format Check

on:
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - id: get-date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ steps.get-date.outputs.date }}-stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: flutter analyze